"""Removed mode column from BasicFilter

Revision ID: 0fbe5c3d8bb3
Revises: 3e2617444160
Create Date: 2023-08-06 23:56:05.795728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fbe5c3d8bb3'
down_revision = '3e2617444160'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basic_filter', schema=None) as batch_op:
        batch_op.drop_column('mode')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basic_filter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
