"""Added mode to BasicFilter

Revision ID: 3e2617444160
Revises: 4940a713bd1b
Create Date: 2023-08-06 21:54:30.454825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e2617444160'
down_revision = '4940a713bd1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basic_filter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basic_filter', schema=None) as batch_op:
        batch_op.drop_column('mode')

    # ### end Alembic commands ###
