"""Added AdvancedFilter

Revision ID: 46c91c3dc7f6
Revises: 52017554d1ca
Create Date: 2024-07-15 17:06:30.411643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46c91c3dc7f6'
down_revision = '52017554d1ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advanced_filter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conditions', sa.String(length=256), nullable=True),
    sa.Column('device_name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['device_name'], ['device.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('advanced_filter')
    # ### end Alembic commands ###
