"""Added path to study and series

Revision ID: 52017554d1ca
Revises: 0fbe5c3d8bb3
Create Date: 2024-03-08 17:09:14.270077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52017554d1ca'
down_revision = '0fbe5c3d8bb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.String(length=256), nullable=True))
        batch_op.create_index(batch_op.f('ix_series_path'), ['path'], unique=False)

    with op.batch_alter_table('study', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.String(length=256), nullable=True))
        batch_op.create_index(batch_op.f('ix_study_path'), ['path'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_path'))
        batch_op.drop_column('path')

    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_series_path'))
        batch_op.drop_column('path')

    # ### end Alembic commands ###
