"""added patient and study table

Revision ID: 644b94f9482d
Revises: 
Create Date: 2023-07-24 14:03:32.360778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '644b94f9482d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient',
    sa.Column('PatientID', sa.String(length=64), nullable=False),
    sa.Column('PatientName', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('PatientID')
    )
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_PatientName'), ['PatientName'], unique=False)

    op.create_table('study',
    sa.Column('StudyInstanceUID', sa.String(length=64), nullable=False),
    sa.Column('StudyDate', sa.DateTime(), nullable=True),
    sa.Column('StudyDescription', sa.String(length=64), nullable=True),
    sa.Column('ModalitiesInStudy', sa.String(length=64), nullable=True),
    sa.Column('PatientID', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['PatientID'], ['patient.PatientID'], ),
    sa.PrimaryKeyConstraint('StudyInstanceUID')
    )
    with op.batch_alter_table('study', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_ModalitiesInStudy'), ['ModalitiesInStudy'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_StudyDate'), ['StudyDate'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_StudyDescription'), ['StudyDescription'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_StudyDescription'))
        batch_op.drop_index(batch_op.f('ix_study_StudyDate'))
        batch_op.drop_index(batch_op.f('ix_study_ModalitiesInStudy'))

    op.drop_table('study')
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_PatientName'))

    op.drop_table('patient')
    # ### end Alembic commands ###
