"""series studies table

Revision ID: 6f5fa746e5fd
Revises: 644b94f9482d
Create Date: 2023-07-24 15:43:03.115400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f5fa746e5fd'
down_revision = '644b94f9482d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series',
    sa.Column('SeriesInstanceUID', sa.String(length=64), nullable=False),
    sa.Column('SeriesDate', sa.DateTime(), nullable=True),
    sa.Column('SeriesDescription', sa.String(length=64), nullable=True),
    sa.Column('Modality', sa.String(length=64), nullable=True),
    sa.Column('PatientID', sa.String(length=64), nullable=True),
    sa.Column('StudyInstanceUID', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['PatientID'], ['patient.PatientID'], ),
    sa.ForeignKeyConstraint(['StudyInstanceUID'], ['study.StudyInstanceUID'], ),
    sa.PrimaryKeyConstraint('SeriesInstanceUID')
    )
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_series_Modality'), ['Modality'], unique=False)
        batch_op.create_index(batch_op.f('ix_series_SeriesDate'), ['SeriesDate'], unique=False)
        batch_op.create_index(batch_op.f('ix_series_SeriesDescription'), ['SeriesDescription'], unique=False)

    op.create_table('instance',
    sa.Column('SOPInstanceUID', sa.String(length=64), nullable=False),
    sa.Column('SOPClassUID', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=True),
    sa.Column('PatientID', sa.String(length=64), nullable=True),
    sa.Column('StudyInstanceUID', sa.String(length=64), nullable=True),
    sa.Column('SeriesInstanceUID', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['PatientID'], ['patient.PatientID'], ),
    sa.ForeignKeyConstraint(['SeriesInstanceUID'], ['series.SeriesInstanceUID'], ),
    sa.ForeignKeyConstraint(['StudyInstanceUID'], ['study.StudyInstanceUID'], ),
    sa.PrimaryKeyConstraint('SOPInstanceUID', 'SOPClassUID')
    )
    with op.batch_alter_table('instance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instance_filename'), ['filename'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instance_filename'))

    op.drop_table('instance')
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_series_SeriesDescription'))
        batch_op.drop_index(batch_op.f('ix_series_SeriesDate'))
        batch_op.drop_index(batch_op.f('ix_series_Modality'))

    op.drop_table('series')
    # ### end Alembic commands ###
