"""Added devices table

Revision ID: 7337f130b058
Revises: 8db23b18e49c
Create Date: 2023-08-03 13:33:57.993031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7337f130b058'
down_revision = '8db23b18e49c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('ae_title', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.Column('imgs_series', sa.String(length=64), nullable=True),
    sa.Column('imgs_study', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_ae_title'), ['ae_title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_ae_title'))
        batch_op.drop_index(batch_op.f('ix_device_address'))

    op.drop_table('device')
    # ### end Alembic commands ###
