"""Added Filter table

Revision ID: 954142b8782d
Revises: 7337f130b058
Create Date: 2023-08-03 16:58:17.522606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '954142b8782d'
down_revision = '7337f130b058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=True),
    sa.Column('value', sa.String(length=64), nullable=True),
    sa.Column('device_name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['device_name'], ['device.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('filter', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_filter_field'), ['field'], unique=False)
        batch_op.create_index(batch_op.f('ix_filter_value'), ['value'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filter', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_filter_value'))
        batch_op.drop_index(batch_op.f('ix_filter_field'))

    op.drop_table('filter')
    # ### end Alembic commands ###
