"""BasicFilter deleted

Revision ID: bab62a99c680
Revises: f005ffe92cc2
Create Date: 2024-07-18 14:27:49.924317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bab62a99c680'
down_revision = 'f005ffe92cc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basic_filter', schema=None) as batch_op:
        batch_op.drop_index('ix_basic_filter_field')
        batch_op.drop_index('ix_basic_filter_value')

    op.drop_table('basic_filter')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basic_filter',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('field', sa.VARCHAR(length=64), nullable=True),
    sa.Column('value', sa.VARCHAR(length=64), nullable=True),
    sa.Column('device_name', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['device_name'], ['device.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('basic_filter', schema=None) as batch_op:
        batch_op.create_index('ix_basic_filter_value', ['value'], unique=False)
        batch_op.create_index('ix_basic_filter_field', ['field'], unique=False)

    # ### end Alembic commands ###
