"""Corrected Instance table declaration error

Revision ID: c71697551827
Revises: 9679401215b9
Create Date: 2023-07-28 16:36:52.069303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c71697551827'
down_revision = '9679401215b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instance_SOPClassUID'), ['SOPClassUID'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instance_SOPClassUID'))

    # ### end Alembic commands ###
