"""Added port column to Device table

Revision ID: e60439e1b5ee
Revises: 954142b8782d
Create Date: 2023-08-03 17:04:54.531522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e60439e1b5ee'
down_revision = '954142b8782d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('port', sa.Integer(), nullable=True))
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=16),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_device_port'), ['port'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_port'))
        batch_op.alter_column('address',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.drop_column('port')

    # ### end Alembic commands ###
