"""Device Filter relationship

Revision ID: f005ffe92cc2
Revises: 46c91c3dc7f6
Create Date: 2024-07-16 13:57:49.449461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f005ffe92cc2'
down_revision = '46c91c3dc7f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conditions', sa.String(length=256), nullable=True),
    sa.Column('device_name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['device_name'], ['device.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('advanced_filter')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advanced_filter',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('conditions', sa.VARCHAR(length=256), nullable=True),
    sa.Column('device_name', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['device_name'], ['device.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('filter')
    # ### end Alembic commands ###
